=== elRohit/ASIX1/LL.Marques/XML/Act3 - DTD/XML -DTD/e3_personaRK.dtd
<!ELEMENT persona (NIF, nom, cognoms, telefons?, correus?, sexe?)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognoms (cognom+)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT telefons (telefon*)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT correus (correu*)>
<!ELEMENT correu (#PCDATA)>
<!ELEMENT sexe (#PCDATA)>

=== elRohit/ASIX1/LL.Marques/XML/Act3/XML -DTD/e3_personaRK.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE persona SYSTEM "e3_personaRK.dtd">
<persona>
    <!-- NIF de la persona -->
    <NIF>12345678A</NIF>
    <!-- Nom de la persona -->
    <nom>Pepe</nom>
    <cognoms>
        <!-- Cognom de la persona -->
        <cognom>Santos Gamba</cognom>
    </cognoms>
    <telefons>
        <!-- TelÃ¨fon de la persona -->
        <telefon>123456789</telefon>
    </telefons>
    <correus>
        <!-- Correu electrÃ²nic de la persona -->
        <correu>pepe.santos@gmail.com</correu>
    </correus>
    <!-- Sexe de la persona -->
    <sexe>M</sexe>
</persona>
