=== elRohit/ASIX1/LL.Marques/XML/Act3 - DTD/XML -DTD/e5_classeRK.dtd
<!ELEMENT classe (tutor, alumne+)>
<!ELEMENT tutor (persona)>
<!ELEMENT alumne (persona)>
<!ELEMENT persona (NIF, nom, cognom+, telefon*, correu*)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT correu (#PCDATA)>

=== elRohit/ASIX1/LL.Marques/XML/Act3 - DTD/XML -DTD/e5_classeRK.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE classe SYSTEM "e5_classeRK.dtd">
<classe>
    <tutor>
        <persona>
            <NIF>12345678A</NIF>
            <nom>Giovanni</nom>
            <cognom>Rossi</cognom>
            <telefon>123456789</telefon>
            <correu>giovanni.rossi@example.com</correu>
        </persona>
    </tutor>
    <alumne>
        <persona>
            <NIF>23456789B</NIF>
            <nom>Giovanna</nom>
            <cognom>Rossi</cognom>
            <cognom>Smith</cognom>
            <telefon>234567890</telefon>
            <correu>giovanna.rossi@example.com</correu>
        </persona>
    </alumne>
    <!-- Afegeix més elements aquí -->
</classe>
