=== elRohit/ASIX1/LL.Marques/XML/Act5 - XSD/a8_comandesRK.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="comandes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="comanda" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="capsalera">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="client">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nom" type="xs:string"/>
                          <xs:element name="adresa" type="xs:string"/>
                          <xs:element name="poblacio" type="xs:string"/>
                          <xs:element name="codi_postal" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="codi" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="forma_de_pagament">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="descripcio" type="xs:string"/>
                          <xs:element name="num_pagaments" type="xs:int"/>
                          <xs:element name="primer_dia" type="xs:date"/>
                          <xs:element name="dies_entre_pagaments" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="codi" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="comercial" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nom" type="xs:string"/>
                          <xs:element name="correu_electronic" minOccurs="0" type="xs:string"/>
                          <xs:element name="mobil" minOccurs="0" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="codi" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="data_comanda">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dia" type="xs:int"/>
                          <xs:element name="mes" type="xs:int"/>
                          <xs:element name="any" type="xs:int"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="data_lliurament" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dia" type="xs:int"/>
                          <xs:element name="mes" type="xs:int"/>
                          <xs:element name="any" type="xs:int"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="linies">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="linia" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="article">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="descripcio" type="xs:string"/>
                              </xs:sequence>
                              <xs:attribute name="codi" type="xs:string"/>
                              <xs:attribute name="unitats" type="unitatsType" default="Un"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="quantitat" type="xs:int"/>
                          <xs:element name="preu_unitari" type="xs:decimal"/>
                          <xs:element name="descompte" minOccurs="0" maxOccurs="2">
                            <xs:complexType>
                              <xs:attribute name="tipus" type="tipusType"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:int"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="unitatsType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Kg"/>
      <xs:enumeration value="Un"/>
      <xs:enumeration value="L"/>
      <xs:enumeration value="m"/>
      <xs:enumeration value="m2"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="comercial"/>
      <xs:enumeration value="pagament_immediat"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== elRohit/ASIX1/LL.Marques/XML/Act5 - XSD/a8_comandesRK.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<comandes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="a8_comandesRK.xsd">
  <comanda>
    <capsalera>
      <client codi="C001">
        <nom>Client 1</nom>
        <adresa>Adreça 1</adresa>
        <poblacio>Població 1</poblacio>
        <codi_postal>CP001</codi_postal>
      </client>
      <forma_de_pagament codi="FP001">
        <descripcio>Descripció 1</descripcio>
        <num_pagaments>1</num_pagaments>
        <primer_dia>2022-01-01</primer_dia>
        <dies_entre_pagaments>30</dies_entre_pagaments>
      </forma_de_pagament>
      <comercial codi="COM001">
        <nom>Comercial 1</nom>
        <correu_electronic>comercial1@example.com</correu_electronic>
        <mobil>1234567890</mobil>
      </comercial>
      <data_comanda>
        <dia>1</dia>
        <mes>1</mes>
        <any>2022</any>
      </data_comanda>
      <data_lliurament>
        <dia>10</dia>
        <mes>1</mes>
        <any>2022</any>
      </data_lliurament>
      <data_lliurament>
        <dia>20</dia>
        <mes>1</mes>
        <any>2022</any>
      </data_lliurament>
    </capsalera>
    <linies>
      <linia numero="1">
        <article codi="A001" unitats="Kg">
          <descripcio>Article 1</descripcio>
        </article>
        <quantitat>2</quantitat>
        <preu_unitari>10.5</preu_unitari>
        <descompte tipus="comercial"/>
      </linia>
      <linia numero="2">
        <article codi="A002" unitats="Un">
          <descripcio>Article 2</descripcio>
        </article>
        <quantitat>5</quantitat>
        <preu_unitari>2.99</preu_unitari>
      </linia>
      <linia numero="3">
        <article codi="A003" unitats="L">
          <descripcio>Article 3</descripcio>
        </article>
        <quantitat>1</quantitat>
        <preu_unitari>5.75</preu_unitari>
        <descompte tipus="pagament_immediat"/>
      </linia>
    </linies>
  </comanda>
  <comanda>
    <capsalera>
      <client codi="C002">
        <nom>Client 2</nom>
        <adresa>Adreça 2</adresa>
        <poblacio>Població 2</poblacio>
        <codi_postal>CP002</codi_postal>
      </client>
      <forma_de_pagament codi="FP002">
        <descripcio>Descripció 2</descripcio>
        <num_pagaments>2</num_pagaments>
        <primer_dia>2022-02-01</primer_dia>
        <dies_entre_pagaments>15</dies_entre_pagaments>
      </forma_de_pagament>
      <comercial codi="COM002">
        <nom>Comercial 2</nom>
        <correu_electronic>comercial2@example.com</correu_electronic>
        <mobil>9876543210</mobil>
      </comercial>
      <data_comanda>
        <dia>2</dia>
        <mes>2</mes>
        <any>2022</any>
      </data_comanda>
      <data_lliurament>
        <dia>15</dia>
        <mes>2</mes>
        <any>2022</any>
      </data_lliurament>
    </capsalera>
    <linies>
      <linia numero="1">
        <article codi="A004" unitats="m2">
          <descripcio>Article 4</descripcio>
        </article>
        <quantitat>3</quantitat>
        <preu_unitari>8.99</preu_unitari>
      </linia>
      <linia numero="2">
        <article codi="A005" unitats="Un">
          <descripcio>Article 5</descripcio>
        </article>
        <quantitat>10</quantitat>
        <preu_unitari>1.5</preu_unitari>
      </linia>
      <linia numero="3">
        <article codi="A006" unitats="Kg">
          <descripcio>Article 6</descripcio>
        </article>
        <quantitat>2</quantitat>
        <preu_unitari>6.25</preu_unitari>
        <descompte tipus="comercial"/>
        <descompte tipus="pagament_immediat"/>
      </linia>
    </linies>
  </comanda>
</comandes>
