=== elRohit/ASIX1/LL.Marques/XML/Act4 - Avc/a1_temporadaRK.dtd
<!ELEMENT temporada (jornada+)>
<!ATTLIST temporada any CDATA #REQUIRED>
<!ELEMENT jornada (partit+)>
<!ATTLIST jornada número CDATA #REQUIRED>
<!ELEMENT partit (data,estadi,local,visitant,resultat,meteo?)>
<!ATTLIST partit número CDATA #REQUIRED>
<!ELEMENT data (#PCDATA)>
<!ELEMENT estadi (#PCDATA)>
<!ATTLIST estadi espectadors CDATA #REQUIRED>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitant (#PCDATA)>
<!ELEMENT resultat (#PCDATA)>
<!ATTLIST resultat local CDATA #REQUIRED>
<!ATTLIST resultat visitant CDATA #REQUIRED>
<!ELEMENT meteo (#PCDATA)>

=== elRohit/ASIX1/LL.Marques/XML/Act4 - Avc/a1_temporadaRK.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporada SYSTEM "a1_temporadaRK.dtd">
<temporada any="2020">
  <jornada número="1">
    <partit número="1">
      <data>05-02-2020</data>
      <estadi espectadors="67000">Twickenham</estadi>
      <local>Anglaterra</local>
      <visitant>Escòcia</visitant>
      <resultat local="34" visitant="34"></resultat>
      <meteo>sol</meteo>
    </partit>
    <partit número="1">
      <data>05-02-2020</data>
      <estadi espectadors="53000">Millenium</estadi>
      <local>Gal·les</local>
      <visitant>Irlanda</visitant>
      <resultat local="24" visitant="16"></resultat>
    </partit>
  </jornada>
  <jornada número="2">
    <partit número="1">
      <data>12-02-2020</data>
      <estadi espectadors="58000">Lansdowne Road</estadi>
      <local>Irlanda</local>
      <visitant>Itàlia</visitant>
      <resultat local="43" visitant="3"></resultat>
      <meteo>vent</meteo>
    </partit>
    <partit número="2">
      <data>12-02-2020</data>
      <estadi espectadors="42000">Murrayfield</estadi>
      <local>Escòcia</local>
      <visitant>França</visitant>
      <resultat local="12" visitant="14"></resultat>
    </partit>
  </jornada>
</temporada>
