=== elRohit/ASIX1/LL.Marques/XML/Act4 - Avc/a3_comandesRK.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT comandes (articles+,sucursal+)>
<!ELEMENT articles (article+)>
<!ELEMENT article (nom,model)>
<!ELEMENT nom (#PCDATA)> 
<!ATTLIST nom  tipus (A | B | C) "A">
<!ELEMENT model EMPTY>
<!ATTLIST model referencia ID #REQUIRED>
<!ATTLIST model tipus CDATA #REQUIRED>
<!ELEMENT sucursal (adreça+,treballador,data,observacio?,nomarticle+)>
<!ATTLIST sucursal codi ID #REQUIRED>
<!ELEMENT adreça (#PCDATA)>
<!ELEMENT treballador (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT observacio (#PCDATA)>
<!ELEMENT nomarticle (unitats,preu,observacions?,termini)>
<!ATTLIST nomarticle codi IDREF #REQUIRED> 
<!ELEMENT unitats (#PCDATA)> 
<!ELEMENT preu (#PCDATA)>
<!ELEMENT observacions (#PCDATA)>
<!ELEMENT termini (#PCDATA)>

=== elRohit/ASIX1/LL.Marques/XML/Act4 - Avc/a3_comandesRK.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comandes SYSTEM "a3_comandesRK.dtd">
<comandes>
    <articles>
        <article>
            <nom>A</nom>
            <model  referencia="_1" tipus="X"/>
        </article>
        <article>
            <nom>B</nom>
            <model referencia="_2" tipus="Y"/>
        </article>
        <article>
            <nom>C</nom>
            <model referencia="_3" tipus="Z"/>
        </article>
        <article>
            <nom>D</nom>
            <model referencia="_4" tipus="W"/>
        </article>
    </articles>
    <sucursal codi="_5">
        <adreça>Adreça 1</adreça>
        <treballador>John Doe</treballador>
        <data>2022-01-01</data>
        <nomarticle codi="_6">
            <unitats>10</unitats>
            <preu>100</preu>
            <termini>2022-01-10</termini>
        </nomarticle>
        <nomarticle codi="_7">
            <unitats>5</unitats>
            <preu>50</preu>
            <termini>2022-01-05</termini>
        </nomarticle>
        <nomarticle codi="_8">
            <unitats>8</unitats>
            <preu>80</preu>
            <termini>2022-01-08</termini>
        </nomarticle>
    </sucursal>
    <sucursal codi="_9">
        <adreça>Adreça 2</adreça>
        <treballador>Jane Smith</treballador>
        <data>2022-02-01</data>
        <nomarticle codi="_10">
            <unitats>15</unitats>
            <preu>150</preu>
            <termini>2022-02-10</termini>
        </nomarticle>
        <nomarticle codi="_11">
            <unitats>3</unitats>
            <preu>30</preu>
            <termini>2022-02-05</termini>
        </nomarticle>
        <nomarticle codi="_12">
            <unitats>6</unitats>
            <preu>60</preu>
            <termini>2022-02-08</termini>
        </nomarticle>
    </sucursal>
    <sucursal codi="_13">
        <adreça>Adreça 3</adreça>
        <treballador>Mike Johnson</treballador>
        <data>2022-03-01</data>
        <nomarticle codi="_14">
            <unitats>20</unitats>
            <preu>200</preu>
            <termini>2022-03-10</termini>
        </nomarticle>
        <nomarticle codi="_15">
            <unitats>4</unitats>
            <preu>40</preu>
            <termini>2022-03-05</termini>
        </nomarticle>
        <nomarticle codi="_16">
            <unitats>7</unitats>
            <preu>70</preu>
            <termini>2022-03-08</termini>
        </nomarticle>
    </sucursal>
</comandes>
