=== elRohit/ASIX1/LL.Marques/XML/Act4 - Avc/a4_comandesRK.dtd
<!ELEMENT comandes (comanda+)>
<!ELEMENT comanda (capçalera,linies)>
<!ELEMENT capçalera (client,forma_de_pagament,comercial?,data_comanda,data_lliurament*)>
<!ELEMENT client (nom,adreça,població,codi_postal)>
<!ATTLIST client codi ID #REQUIRED>
<!ELEMENT forma_de_pagament (descripció,num_pagaments,primer_dia,dies_entre_pagaments)>
<!ATTLIST forma_de_pagament codi ID #REQUIRED>
<!ELEMENT comercial (nom,correu_electrònic?,mòbil?)>
<!ATTLIST comercial codi ID #REQUIRED>
<!ELEMENT data_comanda (dia,mes,any)>
<!ELEMENT data_lliurament (dia,mes,any)*>
<!ELEMENT linies (linia+)>
<!ELEMENT linia (article,quantitat,preu_unitari,descompte*)>
<!ATTLIST linia número ID #REQUIRED>
<!ELEMENT article (descripció)>
<!ATTLIST article codi ID #REQUIRED>
<!ATTLIST article unitats (Kg | Un | L | m | m2) "Un">
<!ELEMENT descompte (#PCDATA)>
<!ATTLIST descompte tipus (comercial | pagament_immediat) #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adreça (#PCDATA)>
<!ELEMENT població (#PCDATA)>
<!ELEMENT codi_postal (#PCDATA)>
<!ELEMENT descripció (#PCDATA)>
<!ELEMENT num_pagaments (#PCDATA)>
<!ELEMENT primer_dia (#PCDATA)>
<!ELEMENT dies_entre_pagaments (#PCDATA)>
<!ELEMENT correu_electrònic (#PCDATA)>
<!ELEMENT mòbil (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT preu_unitari (#PCDATA)>

=== elRohit/ASIX1/LL.Marques/XML/Act4 - Avc/a4_comandesRK.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comandes SYSTEM "a4_comandesRK.dtd">
<comandes>
    <comanda>
        <capçalera>
            <client codi="C1">
                <nom>Client 1</nom>
                <adreça>Adreça 1</adreça>
                <població>Població 1</població>
                <codi_postal>CP1</codi_postal>
            </client>
            <forma_de_pagament codi="FP1">
                <descripció>Descripció 1</descripció>
                <num_pagaments>1</num_pagaments>
                <primer_dia>1</primer_dia>
                <dies_entre_pagaments>30</dies_entre_pagaments>
            </forma_de_pagament>
            <comercial codi="CO1">
                <nom>Comercial 1</nom>
                <correu_electrònic>comercial1@example.com</correu_electrònic>
                <mòbil>123456789</mòbil>
            </comercial>
            <data_comanda>
                <dia>1</dia>
                <mes>1</mes>
                <any>2022</any>
            </data_comanda>
            <data_lliurament>
                <dia>31</dia>
                <mes>1</mes>
                <any>2022</any>
            </data_lliurament>
        </capçalera>
        <linies>
            <linia número="L1">
                <article codi="A1" unitats="Kg">
                    <descripció>Article 1</descripció>
                </article>
                <quantitat>1</quantitat>
                <preu_unitari>10</preu_unitari>
                <descompte tipus="comercial">5</descompte>
            </linia>
            <linia número="L2">
                <article codi="A2" unitats="Un">
                    <descripció>Article 2</descripció>
                </article>
                <quantitat>2</quantitat>
                <preu_unitari>20</preu_unitari>
                <descompte tipus="pagament_immediat">10</descompte>
            </linia>
            <linia número="L3">
                <article codi="A3" unitats="L">
                    <descripció>Article 3</descripció>
                </article>
                <quantitat>3</quantitat>
                <preu_unitari>30</preu_unitari>
            </linia>
        </linies>
    </comanda>
    <!-- Add more comanda elements here -->
</comandes>
